// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWQPu0954oOo8m5Op8-i556-TM4DMWJo',
    appId: '1:870777639417:web:ce90e8d84947fd4c2d6d28',
    messagingSenderId: '870777639417',
    projectId: 'emergency-ai-app',
    authDomain: 'emergency-ai-app.firebaseapp.com',
    storageBucket: 'emergency-ai-app.firebasestorage.app',
    measurementId: 'G-7CERK7SDQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wp5qugs4842WW6kKNbLj-FGg9p0q6Cg',
    appId: '1:870777639417:android:439998fb4e5fb44e2d6d28',
    messagingSenderId: '870777639417',
    projectId: 'emergency-ai-app',
    storageBucket: 'emergency-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1gWtB-ID-tTDCDc3f5VIYyU4llAD27c',
    appId: '1:870777639417:ios:ed0e0e89b39059f02d6d28',
    messagingSenderId: '870777639417',
    projectId: 'emergency-ai-app',
    storageBucket: 'emergency-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.emergencyAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1gWtB-ID-tTDCDc3f5VIYyU4llAD27c',
    appId: '1:870777639417:ios:ed0e0e89b39059f02d6d28',
    messagingSenderId: '870777639417',
    projectId: 'emergency-ai-app',
    storageBucket: 'emergency-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.emergencyAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBWQPu0954oOo8m5Op8-i556-TM4DMWJo',
    appId: '1:870777639417:web:b77cf6ccabb8f79c2d6d28',
    messagingSenderId: '870777639417',
    projectId: 'emergency-ai-app',
    authDomain: 'emergency-ai-app.firebaseapp.com',
    storageBucket: 'emergency-ai-app.firebasestorage.app',
    measurementId: 'G-WN2R4XBJQX',
  );
}
